version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "16:10"
      timezone: "Europe/London"
    open-pull-requests-limit: 1
