version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "17:41"
      timezone: "Europe/London"
    open-pull-requests-limit: 1
    groups:
      non-majors:
        patterns: ["*"]
        update-types: ["minor", "patch"]
