site_name: Splink
site_url: https://moj-analytical-services.github.io/splink/
use_directory_urls: false
repo_url: https://github.com/moj-analytical-services/splink
edit_uri: edit/master/docs/
theme:
  icon:
    repo: fontawesome/brands/github
  name: "material"
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.indexes
    - navigation.footer
    - content.action.edit
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.follow
  logo: "img/favicon.ico"
  favicon: "img/favicon.ico"
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: purple
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  custom_dir: docs/overrides
plugins:
  # I have tried https://github.com/greenape/mknotebooks/blob/master/examples/cell_tag_remove/mkdocs.yml
  # and it doesn't work
  - mknotebooks
  - blog:
      post_date_format: long
      archive: false
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            docstring_style: google
  - charts
hooks:
  - docs/hooks/__init__.py

markdown_extensions:
  - abbr
  - attr_list
  - meta
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: True
      toc_depth: 3
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - footnotes
  - neoteroi.cards
nav:
  - Home: "index.md"
  - Documentation:
    - Introduction: "documentation_index.md"
  - Topic Guides:
    - Comparing Records:
      - Defining and customising comparisons: "topic_guides/comparisons/customising_comparisons.ipynb"
      - Out-of-the-box comparisons: "topic_guides/comparisons/comparison_templates.ipynb"
      - Term-Frequency adjustments: "topic_guides/comparisons/term-frequency.md"
extra_css:
- css/custom.css
- css/neoteroi-mkdocs.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
extra:
  analytics:
    provider: google
    property: G-L6JT8NK528
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/moj-analytical-services/splink
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/splink/
    - icon: fontawesome/solid/chevron-right
      link: https://www.robinlinacre.com/
    - icon: fontawesome/solid/rss
      link: https://moj-analytical-services.github.io/splink/feed_rss_created.xml
  new: Recently added
exclude:
  - "api_docs/**"