site_name: Splink
use_directory_urls: false
repo_url: https://github.com/moj-analytical-services/splink
theme:
  name: "material"
  features:
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - search.highlight
    - search.share
    - search.suggest
  logo: "img/favicon.ico"
  favicon: "img/favicon.ico"
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: purple
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
plugins:
  - search
  - semiliterate
  - mknotebooks
  - tags
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
      custom_templates: templates
markdown_extensions:
  - abbr
  - attr_list
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - toc:
      permalink: True
nav:
  - Home: "README.md"
  - User Guide: "userguide.md"
  - API Reference:
      - Linker API: "linker.md"
      - EM Training Session API: "em_training_session.md"
      - SplinkDataFrame API: "SplinkDataFrame.md"
      - Comparisons API:
          - Comparison: "comparison.md"
          - Comparison Library: "comparison_library.md"
          - Comparison Level: "comparison_level.md"
          - Comparison Level Library: "comparison_level_library.md"
  - Settings Editor: "settingseditor/editor.md"
