# spellchecker: hunspell

matrix:
- name: Markdown docs
  group: docs
  aspell:
    lang: en
    d: en_GB
    mode: markdown
  dictionary:
    wordlists:
    - scripts/pyspelling/custom_dictionary.txt
    output: scripts/dictionary.dic
  sources:
  - docs/getting_started.md
  # - docs/*.md
  # - docs/*/*.md
  # - docs/*/*/*.md
# - name: ipynb docs
#   group: docs
#   aspell:
#     lang: en
#     d: en_US
#   sources:
#   - docs/*/

