name: autoruff
on:
  pull_request:
    branches:
      - master
      - "**dev"
    paths:
      - "**/*.py"
      - "pyproject.toml"

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint with Ruff using Python 3.12.1
    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        id: setup-uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Python 3.12
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync -p 3.12

      - name: Run mypy
        run: uv run mypy splink

      - name: Run Ruff linting
        run: uv run ruff check . --output-format=full

      - name: Run Ruff formatting check
        run: uv run ruff format --check .
