name: Release Package on PyPi
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
jobs:
  poetry-publish:
    environment: 'release'
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
        run: poetry publish --build -u __token__ -p $TOKEN
      # Create duckdbless requirements
      - name: Run duckdbless setup
        run: |
          chmod +x ./scripts/duckdb-less_packages.sh
          ./scripts/duckdb-less_packages.sh
        shell: bash
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update duckdbless requirements
          # feed exact file for ease
          file_pattern: "duckdbless_requirements.txt"
          repository: ./scripts
