# this workflow runs off the back of comment-generation so that it can run in main repo context
# this ensures we have the necessary write permission to post a comment on main repo,
# which would be lacking if this workflow was triggered directly by a PR from a fork
name: Post benchmark comment
on:
  repository_dispatch:
    types: [trigger-pr-comment]

jobs:
  post-benchmark-comment:
    runs-on: ubuntu-20.04
    steps:
      - name: Retrieve comment markdown file artifact
        uses: actions/download-artifact@v3
        env:
          PR_NUMBER: ${{ github.event.client_payload.pr_number }}
        with:
          name: benchmark-markdown-comment-pr-${{ PR_NUMBER }}
          path: benchmark_comment_markdown.md

      - name: Post benchmarking comment
        uses: NejcZdovc/comment-pr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: benchmark_comment_markdown.md
