name: Dataframe backend tests
on:
  pull_request:
    branches:
      - master
      - "**dev"
    paths:
      - "splink/**"
      - "tests/**"
      - "pyproject.toml"
      - "poetry.lock"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
        dataframe-backend: ["pandas", "polars"]
    name: Run tests with Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry using pipx
        run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction --no-root --extras ${{ matrix.dataframe-backend }}
          # check installed library versions
          poetry run python -m pip freeze

      - name: Run tests with coverage
        run: |
          poetry run pytest -v --durations=0 -m "duckdb" tests/
