name: Duckdb and core tests
on:
  pull_request:
    branches:
      - master
      - "**dev"
    paths:
      - "splink/**"
      - "tests/**"
      - "pyproject.toml"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # run lots of versions to catch an error!
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.8", "3.9", "3.10", "3.11", "3.12", "3.8", "3.9", "3.10", "3.11", "3.12", "3.8", "3.9", "3.10", "3.11", "3.12"]
    name: Run tests with Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry using pipx
        run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction --no-root

      - name: Run tests with coverage
        run: |
          poetry add "pytest-cov>=5.0.0"
          poetry run pytest -v --durations=0 -m "duckdb" tests/test_realtime.py
