name: Run splink example notebooks

on:
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/demos/requirements.txt
      #----------------------------------------------
      # Make sure that the demo notebooks run without error
      #----------------------------------------------
      - name: Test DuckDB example notebooks with pytest
        run: |
          python -m pytest --nbmake --nbmake-kernel=python3 docs/demos/examples/duckdb/*ipynb
      - name: Test Spark example notebooks with pytest
        run: |
          python -m pytest --nbmake --nbmake-kernel=python3 docs/demos/examples/spark/*ipynb
      #- name: Test Athena example notebooks with pytest
      #  run: |
      #    python -m pytest --nbmake --nbmake-kernel=python3 examples/athena/*ipynb
      - name: Test SQLite example notebooks with pytest
        run: |
          python -m pytest --nbmake --nbmake-kernel=python3 docs/demos/examples/sqlite/*ipynb
