name: Run splink example notebooks

on:
  pull_request:
    branches:
      - master
      - "**dev"
    paths:
      - "splink/**"
      - "docs/demos/examples/**"
      - "!docs/demos/examples/examples_index.md"
      - "pyproject.toml"
      - "uv.lock"
  workflow_dispatch:

jobs:
  test-notebooks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        test-group: ["duckdb", "spark", "sqlite"]
    name: Test ${{ matrix.test-group }} notebooks with Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        id: setup-uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync -p ${{ matrix.python-version }}

      - name: Run tests
        run: uv run python -m pytest -v --durations=0 -m "postgres_only" tests/

      - name: Install additional requirements from demos_requirements.txt
        run: uv pip install -r docs/demos/data/demos_requirements.txt

      - name: Modify Notebooks to reduce data size
        run: uv run python scripts/reduce_notebook_runtime.py

      - name: Test ${{ matrix.test-group }} example notebooks with pytest
        run: |
          uv run pytest -vv --nbmake -n=auto --nbmake-kernel=python3 --durations=0 docs/demos/examples/${{ matrix.test-group }}/*ipynb
