name: Update comparison symlinks
on:
  pull_request_target:
    types:
      - closed


jobs:
  if_merged:
    if: github.event.pull_request.merged == true && github.repository == 'moj-analytical-services/splink'
    runs-on: ubuntu-20.04
    # only run this workflow on the upstream
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.SPLINK_TOKEN }}
      #----------------------------------------------
      #              run benchmarks and comment
      #----------------------------------------------
      - name: Run benchmark and comment
        run: |
            chmod +x ./scripts/pseudo_symlink_cls.sh
            source ./scripts/pseudo_symlink_cls.sh
        shell: bash
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Update comparison symlinks
            branch: master
            file_pattern: '*comparison*'
