name: Python Example with pytest
on:
  pull_request:
    branch: splink3

permissions:
  contents: write
  deployments: write
  pull-requests: write

jobs:
  benchmark:
    name: Run pytest-benchmark benchmark example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run benchmark and commit results
        run: |
          pip install -r requirements.txt
          pytest benchmarking/test_performance.py --benchmark-min-rounds=2 --benchmark-json benchmarking/output.json -k 'test_sqlite or test_duckdb'
          python benchmarking/combine_benchmarks_timeseries.py

      - uses: harupy/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: benchmark_comment_markdown.md
